# -*- coding: utf-8 -*-
"""auto-responder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AbD0YcmjwifCN0juobnrx9WxuJiXyNX1
"""

import time
import random
from imapclient import IMAPClient
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.parser import BytesParser

# Email account settings
SMTP_HOST = 'smtp.zoho.in'
SMTP_PORT = 465
SMTP_USERNAME = 'utkarshintern@zohomail.in'
SMTP_PASSWORD = 'Pass@123123'

# Autoresponder settings
AUTO_RESPONDER_MESSAGE = "Thank you for your email. I am currently on vacation and will reply to your message when I return."

# Label settings
LABEL_NAME = "Autoresponder"

def check_and_reply_emails():
    with IMAPClient('imap.zoho.in') as server:
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        server.select_folder('INBOX')

        # Search for emails with no prior replies
        messages = server.search('UNANSWERED')

        for msg_id, _ in server.fetch(messages, 'RFC822').items():
            reply_to_email(server, msg_id)

def reply_to_email(server, msg_id):
    # Fetch the email details
    response = server.fetch(msg_id, 'RFC822')
    raw_email = response[msg_id][b'RFC822']
    
    # Parse the raw email
    email_parser = BytesParser()
    email = email_parser.parsebytes(raw_email)

    # Check if the email has been previously replied
    email_has_replies = server.fetch(msg_id, 'FLAGS')[msg_id].get(b'FLAGS', ())

    if len(email_has_replies) == 0:
        # Send autoresponder reply
        reply = MIMEMultipart()
        reply["Subject"] = "Re: " + email['subject']
        reply["From"] = SMTP_USERNAME
        reply["To"] = 'majumdar_utkarsh@srmap.edu.in'

        text = MIMEText(AUTO_RESPONDER_MESSAGE)
        reply.attach(text)

        smtp_server = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT)
        smtp_server.login(SMTP_USERNAME, SMTP_PASSWORD)
        smtp_server.sendmail(SMTP_USERNAME, email['from'], reply.as_string())
        smtp_server.quit()

        server.move([msg_id], LABEL_NAME)
        

def main():
    while True:
        with IMAPClient('imap.zoho.in') as server:
            server.login('utkarshintern', 'Pass@123123')
            check_and_reply_emails()
            time.sleep(random.randint(45, 120))

if __name__ == '__main__':
    main()

!pip install imapclient

